server:
  port: 80
spring:
  redis:
    host: 192.168.5.130
    password: root

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**

        - id: order_route
          uri: lb://service-order
          predicates:
            - Path=/api/order/**

        - id: user_route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**

        - id: cart_route
          uri: lb://service-cart
          predicates:
            - Path=/api/cart/**

        - id: pay_route
          uri: lb://service-pay
          predicates:
            - Path=/api/payment/**

        - id: web_all_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com,gmall.com


app:
  auth:
    anyonturls: #都能访问
      - /js/**
      - /css/**
      - /img/**
      - /static/**
    denyurls:   #都不能访问
      - /rpc/inner/**
    authurls: #登录才能访问
      - /order.html
      - /trade.html
      - /**/auth/**
    loginPage: http://passport.gmall.com/login.html

