server:
  port: 8000

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #thymeleaf前置配置默认在templates
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html