server:
  port: 7000
spring:
  datasource:
    url: jdbc:mysql://192.168.5.130:3306/gmall_product?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#springboot默认上传最大值是1mb 设置最大发送文件100mb以及最大文件100mb
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml

app:
  minio:
    endpoint: http://192.168.5.130:9000
    accessKey: admin
    secretKey: admin123456
    bucket: gmall
